name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            mono: ''
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            mono: 'mono'
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            mono: 'mono'
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v6

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        cat >> "$GITHUB_OUTPUT" << EOF
        build-output-dir=${{ github.workspace }}/build
        vcpkg-exe=${{ github.workspace }}/vcpkg/vcpkg
        vcpkg-toolchain-file=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        binary-cache-url=https://nuget.pkg.github.com/${{ github.actor }}/index.json
        EOF

    - name: Install Mono for nuget
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install mono-complete

    - name: Bootstrap vcpkg
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

    - name: Fetch Nuget
      id: fetch-nuget
      shell: bash
      run: |
        echo -n "nuget-path=" >> "$GITHUB_OUTPUT"
	"${{ steps.strings.outputs.vcpkg-exe }}" fetch nuget | tee >(tail -n 1 >> "$GITHUB_OUTPUT")
	test ${PIPESTATUS[0]} -eq 0

    # Adapted from https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages
    - name: 'Setup NuGet Credentials for the binary cache'
      shell: 'bash'
      run: |
        ${{ matrix.mono }} ${{ steps.fetch-nuget.outputs.nuget-path }} \
          sources add \
          -source "${{ steps.strings.outputs.binary-cache-url }}" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "${{ github.actor }}" \
          -password "${{ secrets.GITHUB_TOKEN }}"
        ${{ matrix.mono }} ${{ steps.fetch-nuget.outputs.nuget-path }} \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -source "${{ steps.strings.outputs.binary-cache-url }}"

    - name: Configure CMake
      env:
        VCPKG_BINARY_SOURCES: "clear;nuget,Github,readwrite"
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=${{ steps.strings.outputs.vcpkg-toolchain-file }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
